### ISSUE TITLE
Error in collector creating wizard

### ISSUE THREAD

**Issue by gikang82** [spaceone-dev/console#2406]

**Comment by gikang82** [comment]
There is an error in collector creating wizard modal.
The location is 'Collector > +Create > Plugin 선택 > 2. Confirm Credentials'
At confirm credentials process, the number of credentials always '0' even though several credentials are existed.

Error message occurs on both console and console-api.
It`s from console-api.

`2022-03-15T04:49:29.544Z [ERROR] tnx-9895cdafcb5e gikang@mz.co.kr POST /statistics/topic/secret-count (Error) => Status: 400
Error: 3 INVALID_ARGUMENT: ERROR_STATISTICS_QUERY: Statistics query failed. (reason = Resource type is undefined. (resource_type = secret.Secret))
    at Object.exports.createStatusError (/opt/spaceone/wconsole-server/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/opt/spaceone/wconsole-server/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/opt/spaceone/wconsole-server/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/opt/spaceone/wconsole-server/node_modules/grpc/src/client_interceptors.js:618:8)
    at Object.onReceiveStatus (/opt/spaceone/wconsole-server/dist/lib/grpc-client/index.js:417:29)
    at InterceptingListener._callNext (/opt/spaceone/wconsole-server/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/opt/spaceone/wconsole-server/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/opt/spaceone/wconsole-server/node_modules/grpc/src/client_interceptors.js:847:24)
    at callbackTrampoline (node:internal/async_hooks:130:17)
2022-03-15T04:49:29.550Z [INFO] tnx-fefe76b965ad gikang@mz.co.kr POST /identity/provider/get (Response) => Status: 200,
                    Response Time: 36 ms, Content Length: 1625`
